Bug/shashank kavli/158#
meshery/play pull request #159
Opened 2023-09-26 16:42 UTC by shashank-kavli

**Notes for Reviewers**

This PR fixes #158

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-09-26 16:46 UTC, shashank-kavli commented
@goldfishdolphin Pls check and lmk if any changes are required. Hoping that I've raised the PR correctly 🤞

2023-09-26 16:56 UTC, goldfishdolphin commented
Looking good 👍🏽

2023-09-28 08:47 UTC, goldfishdolphin requested changes

2023-09-28 08:47 UTC, goldfishdolphin commented on site/src/components/Navigation/Navigation.styles.js
> +        // border-radius:20px;
```suggestion
 
```

2023-09-28 08:47 UTC, goldfishdolphin commented on site/src/components/Navigation/Navigation.styles.js
> +        // border: 1px solid gray
```suggestion
       
```

2023-09-28 08:47 UTC, goldfishdolphin commented on site/src/components/Navigation/index.js
> +            {/* <div className="mode-btn">
```suggestion

```

2023-09-28 08:47 UTC, goldfishdolphin commented on site/src/components/Navigation/index.js
>                <Toggle theme={theme} toggleTheme={toggleTheme} />
```suggestion
         
```

2023-09-28 08:47 UTC, goldfishdolphin commented on site/src/components/Navigation/index.js
> +            </div> */}
```suggestion
        
```

2023-09-28 08:48 UTC, goldfishdolphin commented
Please remove the commented code. Otherwise all good 👍🏽

2023-09-28 17:17 UTC, shashank-kavli commented
@goldfishdolphin I've made the requested changes

2023-09-28 20:33 UTC, goldfishdolphin approved these changes
Thanks @shashank-kavli  for your great work .

2023-10-01 16:13 UTC, saurabh100ni commented
Let's discuss this Item in tomorrow's website call, 
please add it as your agenda if you would: 
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit

2023-11-23 10:51 UTC, closed without merging